manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: bigboiL0st
      url-base: https://github.com/bigboiL0st
  projects:
    - name: zmk
      remote: bigboiL0st
      revision: cresk
      import: app/west.yml
  self:
    path: config
